INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Select the sent ence containing the homonym o f the highlight ed w ord:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'What is the main point o f groupthink as pr esent ed in the p assage?
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'As per the p assage, which ev olutionar y tendency fuels social conformity ?
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Which incident is mentioned as a r eal-life out come link ed to groupthink?
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'How does the p assage say digital platforms str engthen conformity ?
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', '. What r emedy does the p assage r ecommend for gr oupthink and conformity ?
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Choose the most suitable option t o replace the highlight ed part of the sent ence:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Choose the corr ect meaning o f idiom: Blow a fuse', '["To slip away quietly","To vanish suddenly\n\nCopyright © 2026  Adda247","To become suddenly angry","To manage a situation smartly"]'::jsonb, 2, 'The correct option is (c).
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Select the corr ect option:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Choose the most suitable option t o replace the highlight ed part of the sent ence:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Rearrange the following sent ences t o form a coher ent p aragraph:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Find the p art of the sent ence that contains an err or:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Find the p art of the sent ence that contains an err or:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'Vocabulary', 'Synonyms', 'medium', 'Select the most appr opriat e synonym o f the giv en w ord: AMORPHOUS', '["Vague","Clear","Strict","Accurate"]'::jsonb, 0, 'The correct option is (a).
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Identif y the corr ect spelling o f the t erm chr omosomal “thr ee copies” .', '["Trissomie","Trissomy","Trisomy","Trisomie"]'::jsonb, 2, 'The correct option is (c).
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Select the corr ect option:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Select the corr ect option:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'A sent ence is pr ovided in dir ect speech. Fr om the four giv en options, choose the one that most accurat ely conv eys the sent ence in its
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Identif y the corr ect one-w ord substitut e for : “A condition o f disuse or inactivity .”', '["Interregnum","Destitute","Lethargy","Desuetude"]'::jsonb, 3, 'The correct option is (d).
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Change the following fr om activ e to passiv e:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Series', 'Letter Series', 'easy', 'Select the option that will correctly fill all the blanks in the series: m _ n m _ n _ _ n m _ _', '["a a a m n a","a a m a a n","m n o o o o","a a m n m a"]'::jsonb, 0, 'The pattern follows repetition of ''m a n''. Filling accordingly gives: m a n m a n m a n m a n. Thus, correct option is (0).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Number Logic', 'Pattern Based', 'easy', 'If 5 + 3 = 16 and 7 + 4 = 33, then 6 + 2 = ?', '["32","14","16","18"]'::jsonb, 0, 'Pattern: a^2 - b^2. 6^2 - 2^2 = 36 - 4 = 32. Thus, correct option is (0).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Series', 'Number Series', 'easy', 'What number will replace the question mark? 2, 6, 14, 30, ?, 126', '["46","60","62","64"]'::jsonb, 2, 'Pattern: multiply by 2 and add 2. 30×2+2=62. Thus, correct option is (2).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Logical Reasoning', 'Statement and Assumption', 'medium', 'Statement: Excessive use of plastic bags harms the environment. Assumptions: I. Plastic bags are non-biodegradable. II. People are aware of environmental damage caused by plastic.', '["Only I is implicit","Only II is implicit","Both I and II are implicit","Neither I nor II is implicit"]'::jsonb, 0, 'Assumption I explains why plastic harms environment. II is unrelated. Thus, correct option is (0).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Series', 'Number Series', 'easy', 'Complete the series: 3, 9, 27, ?, 243', '["54","72","81","90"]'::jsonb, 2, 'Pattern: multiply by 3. 27×3=81. Thus, correct option is (2).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'Polity', 'Indian Constitution', 'easy', 'Find the odd one out: Article 14, Article 19, Article 21, Article 360', '["Article 14","Article 19","Article 21","Article 360"]'::jsonb, 3, 'Article 360 is Emergency provision, others are Fundamental Rights. Thus, correct option is (3).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Coding-Decoding', 'Letter Coding', 'easy', 'If CAT is written as 3-1-20 and DOG as 4-15-7, how will PIG be written?', '["16-9-7","15-9-7","16-8-7","15-8-6"]'::jsonb, 0, 'Alphabet positions: P=16, I=9, G=7. Thus, correct option is (0).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Mathematical Operations', 'Operator Replacement', 'medium', 'If ''+'' means ''×'', ''−'' means ''+'', ''×'' means ''÷'', and ''÷'' means ''−'', find value of 18 − 6 + 12 × 3 ÷ 2', '["8","40","10","12"]'::jsonb, 1, 'Replace operators → 18+6×12÷3−2 = 40. Thus, correct option is (1).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'Accuracy', 'Identical Sentences', 'easy', 'Choose the address exactly identical to: Flat 402, Emerald Residency, Lake View Road, Pune, Maharashtra – 411016', '["Flat 402 Emerald Residency Lakeview Road Pune Maharashtra 411016","Flat 402, Emerald Residency, Lake View Rd., Pune, Maharashtra – 411061","Flat 420, Emerald Residency, Lake View Road, Pune, Maharashtra – 411016","Flat 402, Emerald Residency, Lake View Road, Pune, Maharashtra – 411016"]'::jsonb, 3, 'Only option D matches exactly. Thus, correct option is (3).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Average', 'easy', 'What is the average of the first 7 odd numbers?', '["6","7","8","9"]'::jsonb, 1, 'Average = middle term = 7. Thus, correct option is (1).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Ratio and Proportion', 'easy', 'Ratio of two numbers is 7:9 and sum is 256. Find numbers.', '["98 and 126","112 and 144","119 and 137","126 and 130"]'::jsonb, 1, 'Total parts=16, each=16 → numbers=112,144. Thus, correct option is (1).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'Art and Culture', 'Indian Classical Dance', 'easy', 'Match the classical dance form with its state of origin: 1. Sattriya 2. Kuchipudi 3. Mohiniyattam', '["1-Assam, 2-Andhra Pradesh, 3-Kerala","1-Kerala, 2-Assam, 3-Andhra Pradesh","1-Andhra Pradesh, 2-Kerala, 3-Assam","1-Assam, 2-Kerala, 3-Andhra Pradesh"]'::jsonb, 0, 'Sattriya originates from Assam, Kuchipudi from Andhra Pradesh, and Mohiniyattam from Kerala. Thus, correct option is (0).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'Polity', 'Fundamental Duties', 'easy', 'Which of the following is a fundamental duty under Article 51A of the Indian Constitution?', '["To provide free legal aid","To protect and improve the natural environment","To organize village panchayats","To separate the judiciary from the executive"]'::jsonb, 1, 'Article 51A(g) mentions protecting environment. Thus, correct option is (1).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'Science', 'Chemistry', 'easy', 'Which chemical element produces green colour in firework displays?', '["Strontium","Barium","Sodium","Copper"]'::jsonb, 1, 'Barium produces green color. Thus, correct option is (1).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'Geography', 'Rivers of India', 'easy', 'Which river originates from the Amarkantak Plateau?', '["Godavari","Narmada","Krishna","Kaveri"]'::jsonb, 1, 'Narmada originates from Amarkantak Plateau. Thus, correct option is (1).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'Sports', 'Important Facts', 'easy', 'What is the standard distance of a Marathon race?', '["21.09 km","42.195 km","50 km","38.5 km"]'::jsonb, 1, 'Standard marathon distance is 42.195 km. Thus, correct option is (1).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Blood Relations', 'medium', 'P is the sister of Q. R is the father of Q. How is R related to P?', '["Father","Uncle","Brother","Grandfather"]'::jsonb, 0, 'Given: P is the sister of Q. R is the father of Q. From the given information blood relation diagram will be. So, R is father of P. Thus, correct option is (a).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Classification', 'medium', 'Find the odd one out:', '["Copper","Iron","Gold","Plastic"]'::jsonb, 3, 'Copper, iron and gold are metals. Plastic is a non-metal. So, plastic is odd one out. Thus, correct option is (d).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'A 20 L mixture contains milk and water in the ratio 2:3. How much milk must be added to make the ratio 4:3?', '["10 L","8 L","5 L","9 L"]'::jsonb, 1, 'Given: A 20 L mixture contains milk and water in the ratio 2:3. Solution: Milk : Water = 2 : 3 Total mixture = 20 L Milk = 2/5 * 20 = 8 L Water = 3/5 * 20 = 12 L Let (x) L milk be added. (8 + x)/12 = 4/3 3(8 + x) = 48 8 + x = 16 x = 8 Required milk = 8 L So, 8 L milk must be added to make the ratio 4:3. Thus, correct option is (b).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'If + = ×, - = ÷, × = +, ÷ = -, then find: 24 + 6 - 2 × 4 ÷ 2 = ?', '["76","72","78","74"]'::jsonb, 3, 'Given: 24 + 6 - 2 × 4 ÷ 2 = ? Given Sign + - × ÷ New Sign × ÷ + - Using BODMAS rule. New equation: 24 × 6 ÷ 2 + 4 - 2 = ? 24 × 3 + 4 - 2 = ? 72 + 4 - 2 = ? 76 - 2 = ? ? = 74 Thus, correct option is (d).');