TRUNCATE public.questions CASCADE;

INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Miscellaneous', 'medium', 'If a % b = a² - b² and a % b = 63, find a and b.', '["9, 6","10, 7","8, 1","7, 4"]'::jsonb, 2, 'Given :
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Alphabet Test', 'medium', 'How many lett ers will r emain unchanged if the w ord EDUCA TION is arranged alphabetically ?', '["One","Zero","Three","Two"]'::jsonb, 1, 'Given : EDUCA TION
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'Select the lett er-clust er that will r eplace (?):
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Blood Relations', 'medium', 'Pointing t o a boy , a w oman said, “He is the son o f my father ’s only daught er.” How is the boy r elated to the w oman?', '["Son","Brother","Nephew","Cousin"]'::jsonb, 0, 'Given :
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'If 4 ⊕ 3 = 19 and 5 ⊕ 2 = 17, then 6 ⊕ 4 = ?', '["24","28","34","32"]'::jsonb, 2, 'Given :
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Mathematical Reasoning', 'medium', 'If 3x + 7 = 28, find x.', '["7","6","5\n\nCopyright © 2026  Adda247","8"]'::jsonb, 0, 'Given :
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'Apply the same p attern used in the following gr oup and find the corr ect option.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'If ''+'' = ''-'' and ''-'' = ''×'', find the v alue o f:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Miscellaneous', 'medium', 'Find the odd one out.', '["4 : 16 : 256","3 : 9 : 81","5 : 25 : 125","6 : 36 : 1296"]'::jsonb, 2, 'Logic : (1st number) = 2nd number, (2nd number) = 3rd number
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'Eight people P , Q, R, S, T , U, V , W sit ar ound a cir cle facing the cent er. P is second right o f Q. R is opposit e P. S is immediat e left of R. T is thir d to the
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'Find the missing t erm in the series.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'What will come in place o f (?)
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'Which w ord cannot be formed fr om DEMOCRA CY?', '["READY","CORE","MAYOR","CAREER"]'::jsonb, 3, 'Given : DEMOCRA CY
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'What comes next ?
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Coding-Decoding', 'medium', 'In a cer tain code language, "apple is sw eet fruit" is writt en as "ka lo mi t e", "mango is sw eet" is writt en as "lo mi ra" and "apple mango fr esh" is
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Mathematical Reasoning', 'medium', 'The ratio o f two number s is 5 : 7 and their sum is 96. Find the number s.', '["40, 56","45, 51","48, 48","35, 61"]'::jsonb, 0, 'Given :
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Blood Relations', 'medium', 'If A is the br other o f B, and B is the mother o f C, how is A r elated to C?', '["Brother","Father\n\nCopyright © 2026  Adda247","Uncle","Cousin"]'::jsonb, 2, 'Given :
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Coding-Decoding', 'medium', 'If “ROAD” is coded as *4@# and “RE AD” as *@4#, what is the code for “RA OD”?', '["*@#4","*4#@","*@4#","*#@4"]'::jsonb, 2, 'Given :
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'In a t ournament o f 9 play ers, each plays ev ery other play er once. How many mat ches ar e play ed?', '["72","40","42","36"]'::jsonb, 3, 'Given :
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Miscellaneous', 'medium', 'Identif y the similar addr ess:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Miscellaneous', 'medium', 'Statement :
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'If 8 $ 3 = 32 and 6 $ 4 = 30, then 5 $ 4 = ?', '["28","20","24","25"]'::jsonb, 3, 'Given :
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'If + means × and - means ÷, which is incorr ect?', '["8 - 2 + 3 = 12","6 + 3 - 2 = 9","4 - 2 + 5 = 15","9 + 1 - 3 = 3"]'::jsonb, 2, 'Given :
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'Apply the same p attern used in the following gr oup and find the corr ect option.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Reasoning', 'Verbal Reasoning', 'Series', 'medium', 'Find the missing t erm:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'On Electrical Safety Day 2025, MoS P ower and New & R enewable Ener gy Shri Shrip ad Naik unv eiled:', '["National Fire Safety Code","Suraksha Shakti mascot","Smart Meter R ollout Initiative","Grid Digitalization Platform"]'::jsonb, 1, 'The correct answer is (b) Suraksha Shakti mascot.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Anglo-Indian nomination in S tate Assemblies was t erminat ed by:', '["Governor''s ongoing nomination power","42nd Amendment","104th Amendment","Proportional representation election"]'::jsonb, 2, 'The correct answer is (c) 104th Amendment.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Which is generally not classified as a w eather p aramet er?', '["Temperature","Humidity","Soil pH","Wind"]'::jsonb, 2, 'The correct answer is (c) Soil pH.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'Indian Culture', 'Art & Culture', 'medium', 'Which p air corr ectly p airs a temple r oof type with its structural featur e?', '["Latina – rectangular, wagon-like","Phamsana – flat slabs sloping upward to a ridge","Valabhi – steeply curving inward","Latina – wide with tiered steps"]'::jsonb, 1, 'The correct answer is (b) Phamsana – flat slabs sloping upward to a ridge.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Strict r egulation o f crick et ball w eight and size in int ernational games ensur es:', '["Advantage to bowlers with heavier balls, batsmen with lighter ones","Consistent bounce, swing, and equity on uniform pitches","Cost savings as per IC C rules","Applies solely to red balls"]'::jsonb, 1, 'The correct answer is (b) Consistent bounce, swing, and equity on uniform pitches.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Bharatiya Nagarik Suraksha Sanhita (BNSS) intr oduces:', '["Full replacement of IPC provisions","Video recording of confessions","Assumption of guilt","Elimination of bail provisions"]'::jsonb, 1, 'The correct answer is (b) Video recording of confessions.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'Indian Culture', 'Art & Culture', 'medium', 'Order these classical dance forms by their earliest document ed mentions (earliest fir st):
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'The T utsa tribe o f Arunachal Pradesh obser ves the P ongtu Festiv al mainly t o inv oke blessings fr om which god prior t o millet sowing?
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'What charact erizes the book ‘Hot S tage’?', '["Anthology of contemporary Indian plays addressing societal concerns","Chronicle of the independence movement","Mythological fiction","Narrative of Himalayan journeys"]'::jsonb, 0, 'The correct answer is (a) Anthology of contemporary Indian plays addressing societal concerns.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Asser tion (A): Ir on and st eel qualifies as a heavy industr y.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Regarding the 61st National Chess Championship:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Asser tion (A): PSL V is ISR O''s reliable mainstay launch v ehicle.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'IMD W orld Competitiv eness Ranking 2025 shows S witzerland t opping which dimension in both 2024 and 2025?', '["Business Efficiency","Infrastructure","Economic P erformance","Employment"]'::jsonb, 1, 'The correct answer is (b) Infrastructure.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'Indian Culture', 'Art & Culture', 'medium', 'Kalbelia dance symbolizes the sinuous motion o f ______.', '["Camels","Snakes","Birds","Horses"]'::jsonb, 1, 'The correct answer is (b) Snakes.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'On MISHTI Scheme: