INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Who claimed India’ s inaugural P aralympic ar chery gold at P aris 2024?', '["Sheetal Devi","Harvinder Singh","Rakesh Kumar","Preethi P al"]'::jsonb, 1, 'The correct answer is (b) Harvinder Singh.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Asser tion (A): Chotanagpur Plat eau forms the east ern continuation o f Central Highlands.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'The BRICS For eign Minist ers'' Meeting on 4 June 2018 t ook place in which city ?', '["Pretoria, South Africa","Brasília, Brazil","Beijing, China","New Delhi, India"]'::jsonb, 3, 'The correct answer is (d) New Delhi, India.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'Indian Polity', 'Constitution', 'medium', 'Abrogation o f Article 370'' s special status for J ammu and Kashmir occurr ed via:', '["Presidential Order under Article 370(3)","Parliamentary amendment under Article 368","Presidential Ordinance","Article 356 Order"]'::jsonb, 0, 'The correct answer is (a) Presidential Order under Article 370(3).
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Which pr ogram enables postmen t o deliv er financial ser vices?', '["NSAP","IPPB","PMJAY","PRAGATI"]'::jsonb, 1, 'The correct answer is (b) IPPB.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'In Teen T aal fr om Hindustani music, the Khali beat falls on the ______ matra.', '["1","5","9","13"]'::jsonb, 2, 'The correct answer is (c) 9.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Appr oval by both Houses o f Parliament for a National Emer gency Pr oclamation is needed within:', '["1 month","3 months","6 months","9 months"]'::jsonb, 0, 'The correct answer is (a) 1 month.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'The 2025 ‘Mangr ove Cell’ pr ogram is associat ed primarily with which stat e?', '["Odisha","Andhra Pradesh","Maharashtra\n\nCopyright © 2026  Adda247","West Bengal"]'::jsonb, 2, 'The correct answer is (c) Maharashtra.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'Non-metallic minerals in India ar e best described as:', '["Scarce for industrial applications","Mainly gemstones with little industry role","Abundant and essential for key sectors","Secondary to metallic minerals in growth"]'::jsonb, 2, 'The correct answer is (c) Abundant and essential for key sectors.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'General Knowledge', 'General Knowledge', 'Current Affairs', 'medium', 'The initial module o f Bharatiya Antariksh S tation (BAS) is slat ed for launch in:', '["2028","2030","2035","2040"]'::jsonb, 0, 'The correct answer is (a) 2028.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Profit & Loss', 'medium', 'A shopk eeper sells rice at a discount o f 6% on the mark ed price but uses a w eight that is 25% less than the actual w eight. Find his ov erall pr ofit
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Profit & Loss', 'medium', 'The pr ofit made on an ar ticle sold for ₹2400 is equal t o the loss incurr ed when it is sold for ₹2000. What will be the pr ofit or loss per centage if the
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Mensuration', 'Geometry', 'medium', 'A right cir cular cone has a radius o f 9 cm and a height o f 40 cm. What is its slant height ?', '["41 cm","42 cm","43 cm","45 cm"]'::jsonb, 0, 'Given:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'General Math', 'medium', 'If 40% o f P = 0.5 o f Q = 1/8 o f R, find P : Q : R.', '["5 : 4 : 16","4 : 5 : 16","2 : 5 : 8","4 : 5 : 8"]'::jsonb, 0, 'Given:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'General Math', 'medium', 'Evaluat e:', '["266.6 km","285.5 km","248.6 km","320 km"]'::jsonb, 2, '15  % of 480 km +3158  % of 300 km31
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Profit & Loss', 'medium', 'A sales agent earns 3% commission on lapt ops priced at ₹40,000 each and 8% commission on print ers priced at ₹8,000 each. If in a w eek he sells 4
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Mensuration', 'Geometry', 'medium', 'The radius o f a cir cular plat e is incr eased by 8%. What will be the appr oximat e per centage incr ease in its ar ea?', '["8%","15%","16.64%","17.28%"]'::jsonb, 2, 'Given:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Mensuration', 'Geometry', 'medium', 'A rectangular prism has a b ase ar ea of 36 cm². If its height is incr eased by 25% fr om the original height o f 12 cm, what is the new v olume?', '["432 cm³","486 cm³","504 cm³","540 cm³"]'::jsonb, 3, 'Given:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Mensuration', 'Geometry', 'medium', 'A solid metal spher e of radius 6 cm is complet ely immer sed in a v ertical cylindrical v essel containing wat er, causing the wat er lev el to rise by 4 cm.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Time & Distance', 'medium', 'A train cov ers 1.2 km in 1 minut e. How far will it trav el in 2 hour s 15 minut es?', '["162 km","156 km","171 km","168 km"]'::jsonb, 0, 'Given:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Ratio & Proportion', 'medium', 'Two farmer s, X and Y , hire a field. X k eeps 18 o xen ther e for 5 months and 20 go ats for 3 months. Y k eeps 24 go ats for 7 months and 30 sheep for 6
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Ratio & Proportion', 'medium', 'Three batches o f students hav e average ages 17, 19, and 23 y ears respectiv ely. If their number s are in the ratio 3 : 4 : 6, what is the ov erall av erage
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Algebra', 'medium', 'The av erage o f 13 number s is 75. If the av erage o f the fir st six number s is 69 and the av erage o f the last six number s is 80, what is the 7th
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Algebra', 'medium', 'What is the av erage o f all int egers betw een 200 and 350 that ar e exactly divisible by 11?', '["275","272","286","292"]'::jsonb, 0, 'Given:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Algebra', 'medium', 'How many kilograms o f wheat costing ₹52 per k g must be mix ed with 30 k g of wheat costing ₹40 per k g so that a 20% gain may be obtained by
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Mensuration', 'Geometry', 'medium', 'A gar dener has 80 m o f fencing wir e. He can use this wir e to enclose either a cir cular lawn or a squar e lawn. If he uses the entir e wir e in each case,
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'General Math', 'medium', 'Simplif y:', '["0","1","2","√3"]'::jsonb, 0, '+ (
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Ratio & Proportion', 'medium', 'A family spends on gr oceries, r ent, and other expenses in the ratio 3 : 5 : 2. Next y ear, groceries ar e expect ed to rise by 8%, r ent by 4%, and other
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Profit & Loss', 'medium', 'C and D inv ested ₹1,40,000 and ₹1,80,000, r espectiv ely. C remained for 9 months and D for 8 months. If C'' s shar e in the pr ofit is ₹18,900, what is
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Profit & Loss', 'medium', 'A television set is sold for ₹Q and the shopk eeper earns a pr ofit of 25%. During a clearance sale, he marks the same set at 1.4Q and allows a
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Profit & Loss', 'medium', 'A trader marks his goods 30% abov e the cost price and then allows a discount o f 12%. What is his pr ofit per centage?', '["14.4%","15.6%","16.5%","18.0%"]'::jsonb, 0, 'Given:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Profit & Loss', 'medium', 'A shopk eeper marks his pr oducts 50% abov e the cost price and allows a discount o f 20% on the mark ed price. He also giv es an additional cash
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Algebra', 'medium', 'X lent ₹6,000 t o Y for 3 y ears and ₹4,000 t o Z for 2 y ears, both at the same simple int erest rat e. In t otal, he r eceiv ed ₹2,000 as int erest fr om both.
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Mensuration', 'Geometry', 'medium', 'A sect or of a cir cle has a central angle o f 150° and radius 10 cm. Another sect or of the same cir cle has a central angle o f 5π/6 radians. What is the
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'Mathematics', 'Arithmetic', 'Ratio & Proportion', 'medium', 'Two men, M and N, r ent a p astur e. M uses 12 cows for 4 months and 18 go ats for 5 months, while N uses 26 go ats for 7 months. If 3 cows ar e
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Select the most appr opriat e ant onym o f the giv en w ord: Polymathic', '["Intellectual","Uninformed","Skilled","Saintly"]'::jsonb, 1, 'The correct option is (b).
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Select the most appr opriat e ant onym o f the giv en w ord: Eulogy', '["Panegyric","Tributary","Castigation","Pronunciation"]'::jsonb, 2, 'The correct option is (c).
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Conv ert the sent ence pr ovided below fr om its p assiv e voice structur e to an activ e voice structur e:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'Rearrange the following sent ences in corr ect or der t o mak e a logical p assage:
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'English Language', 'Miscellaneous', 'medium', 'A sent ence is pr ovided in indir ect speech. Fr om the four giv en options, choose the one that most accurat ely conv eys the sent ence in its