INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'General', 'General', 'medium', 'Convert the sentence provided below from its passive voice structure to an active voice structure: A decision has been made to get the manuscript reviewed by an external committee.', '["An external committee has reviewed the manuscript.","The manuscript is being reviewed by an external committee.","They have decided to get the manuscript reviewed by an external committee.","The manuscript was reviewed by the committee as per the decision."]'::jsonb, 2, 'Active form: “They have decided...”. Thus, correct option is (c).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'General', 'General', 'medium', 'Select the most appropriate option to substitute the underlined segment in the given sentence. She is confidentof to clear the interview.', '["of to clear","that she clears","of clearing the","on clearing interview"]'::jsonb, 2, '“confidentof clearing the”. Thus, correct option is (c).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'Reading Comprehension', 'Passage Based', 'medium', 'What concern does the passage raise about Yoga’s worldwide popularity?', '["Lack of studios","Dilution of its philosophical foundation","Shortage of practitioners","Excess control by Indian agencies"]'::jsonb, 1, 'The passage mentions dilution of philosophical foundation. Thus, correct option is (b).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'General', 'General', 'medium', 'Which option best represents the Ayurvedic view of illness, as discussed?', '["Destroying pathogens through antibiotics","Using synthetic drugs for instant relief","Rebalancing the body through lifestyle and routine","Correcting genetic defects directly"]'::jsonb, 2, 'Ayurveda focuses on rebalancing the body. Thus, correct option is (c).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'Reading Comprehension', 'Passage Based', 'medium', 'What risk linked to institutional promotion of AYUSH is mentioned in the passage?', '["Rising production costs","Increased rural joblessness","Traditional knowledge holders being sidelined","Dependence on foreign investors"]'::jsonb, 2, 'Marginalization of traditional knowledge holders. Thus, correct option is (c).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'General', 'General', 'medium', 'What position does the author take regarding combining traditional medicine with modern healthcare?', '["Traditional systems should replace allopathy","Modern medicine must reject tradition","Integration can work with humility and regulation","Both should remain strictly separate"]'::jsonb, 2, 'Integration with humility and regulation. Thus, correct option is (c).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'Reading Comprehension', 'Passage Based', 'medium', 'According to the passage, what is essential for the continued relevance of Yoga and traditional medicine in India?', '["Complete isolation from modern science","Preserving philosophical depth while applying rigorous scrutiny","Ignoring clinical trials","Focusing only on commercial appeal"]'::jsonb, 1, 'Preserving depth while applying scrutiny. Thus, correct option is (b).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'Vocabulary', 'Spelling Test', 'medium', 'Find the word that is spelled correctly and means light, witty banter.', '["Persiflage","Persiflaige","Persiphlege","Persiflagee"]'::jsonb, 0, 'Persiflage is the correct spelling. Thus, correct option is (a).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'Grammar', 'Direct/Indirect Speech', 'medium', 'The researcher said, “We have been observing this phenomenon for months.”', '["The researcher said they had been observing that phenomenon for months.","The researcher said they have been observing this phenomenon for months.","The researcher said that they were observing that phenomenon.","The researcher said that we had observed this phenomenon."]'::jsonb, 0, '“have been observing” becomes “had been observing”. “this” becomes “that”. Thus, correct option is (a).');
INSERT INTO public.questions (exam, subject, subtopic, chapter, difficulty, question_text, options, correct_option, solution_text) VALUES ('SSC CGL', 'English', 'General', 'General', 'medium', 'Select the sentence containing the homonym of the highlighted word: The bishop denounced the act as simony, citing church law.', '["The cleric was charged with simony for selling sacred offices.","Historians noted that simony corrupted many medieval appointments.","The chemist measured the simony of the compound under pressure.","Simony was condemned repeatedly by reform councils."]'::jsonb, 2, 'In (C), simony is used as a scientific property, which is a homonym usage. Thus, correct option is (c).');

UPDATE public.test_sessions SET subject = 'Mathematics' WHERE subject = 'Quantitative Aptitude';
UPDATE public.test_sessions SET subject = 'Reasoning' WHERE subject = 'General Intelligence & Reasoning';
UPDATE public.test_sessions SET subject = 'General Knowledge' WHERE subject = 'General Awareness';
UPDATE public.test_sessions SET subject = 'English' WHERE subject = 'English Comprehension';